# Define a imagem base como bitnami/php-fpm com a tag latest
FROM bitnami/php-fpm:latest

# Atualiza o repositório de pacotes e instala o pacote 'unzip'
RUN apt-get update && apt-get install -y \
    unzip